/*
ROM - Read Only Memory

stores the info of the the sprites to be initially generated by the spu


a .txt file is read like a normal rom chip,then the data is output to the ram,conditioned by the spu



*/


module rom (
            clk,    // memory clk
            address,    // pointer signals
            data    // memory output data
            );


output [8:0] data;
input [15:0] address;

input wire clk;

reg [8:0] data;
wire [15:0] address;






endmodule